version: "3"

services:
  hyperf:
    image: hyperf/hyperf
    container_name: hyperfIm
    networks:
      - hyperfIm
    volumes:
      - ./:/hyperf-skeleton:rw
    ports:
      - "9501:9501"
    command: ["php","/hyperf-skeleton/bin/hyperf.php","start"]
  hyperf-mysql:
    image: mysql:5.7
    container_name: hyperf-mysql
    networks:
      - hyperfIm
    ports:
      - "3306:3306"
    volumes:
      - ./runtime/mysql/data:/var/lib/mysql:rw
      - ./runtime/mysql/sock:/var/run/mysqld:rw
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: im
      MYSQL_USER: im
      MYSQL_PASSWORD: im-password
  hyperf-redis:
    image: redis:5.0
    container_name: hyperf-redis
    networks:
      - hyperfIm
    ports:
      - "6379:6379"
    volumes:
      - ./runtime/redis/data:/var/lib/redis:rw
networks:
  hyperfIm: